[package]
name = "cli"
version.workspace = true
edition = "2021"

[[bin]]
name = "borehole"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
owo-colors = { workspace = true }
anyhow = { workspace = true }
webpki-roots = { workspace = true }
dirs = "5"
common = { path = "../common" }
ureq = { version = "3.3.0", features = ["json"] }
semver = "1.0.28"
self-replace = "1.5.0"
tempfile = "3.27.0"
